spring.application.name=demo

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://gokulkavya149_db_user:COM81LFAkf7J2u7X@cluster0.lzarsma.mongodb.net/SmartATS?retryWrites=true&w=majority&tlsAllowInvalidCertificates=true}

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:gokulkavya149@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hzboxnkudhlmwimy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true